export default {
  //LOGIN
  LOGIN_USER_REQUEST: "LOGIN_USER_REQUEST",
  LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
  LOGIN_USER_FAILURE: "LOGIN_USER_FAILURE",

  //PROFILE
  GET_PROFILE_REQUEST: "GET_PROFILE_REQUEST",
  GET_PROFILE_SUCCESS: "GET_PROFILE_SUCCESS",
  GET_PROFILE_FAILURE: "GET_PROFILE_FAILURE",
  
  //PRODUCTS
  GET_PRODUCTS_REQUEST: "GET_PRODUCTS_REQUEST",
  GET_PRODUCTS_SUCCESS: "GET_PRODUCTS_SUCCESS",
  GET_PRODUCTS_FAILURE: "GET_PRODUCTS_FAILURE",

  //Cart list
  GET_CART_LIST_REQUEST: "GET_CART_LIST_REQUEST",
  GET_CART_LIST_SUCCESS: "GET_CART_LIST_SUCCESS",
  GET_CART_LIST_FAILURE: "GET_CART_LIST_FAILURE",

  //Cards
  GET_ALL_CARD_REQUEST: "GET_ALL_CARD_REQUEST",
  GET_ALL_CARD_SUCCESS: "GET_ALL_CARD_SUCCESS",
  GET_ALL_CARD_FAILURE: "GET_ALL_CARD_FAILURE",

  //Cards
  GET_ALL_ORDERS_REQUEST: "GET_ALL_ORDERS_REQUEST",
  GET_ALL_ORDERS_SUCCESS: "GET_ALL_ORDERS_SUCCESS",
  GET_ALL_ORDERS_FAILURE: "GET_ALL_ORDERS_FAILURE",
};
