export const routeName = {
  LANDING_SCREEN: "LANDING_SCREEN",
  SPLASH: 'SPLASH',
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',
  PERSONAL_INFO: 'PERSONAL_INFO',
  VERIFY_NUMBER: 'VERIFY_NUMBER',
  VERIFICATION: 'VERIFICATION',
  FORGET_PASSWORD: 'FORGET_PASSWORD',

  BOTTOM_TABS: 'BOTTOM_TABS',
  SIDE_DRAWER: 'SIDE_DRAWER',
  HOME_STACK: 'HOME_STACK',

  DASHBOARD: 'DASHBOARD',
  PRODUCT_DETAIL: 'PRODUCT_DETAIL',
  MY_ORDERS: 'MY_ORDERS',
  ORDER_DETAIL: 'ORDER_DETAIL',

  //cart

  CART_LIST: 'CART_LIST',
  CHECKOUT: 'CHECKOUT',
  PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',

  //MORE

  MORE: 'MORE',
  CARD_MANAGEMENT: 'CARD_MANAGEMENT',
  ADD_CARD: 'ADD_CARD',
  PROFILE: 'PROFILE'

};
